#!bin/bash


export CONT_REQUISICOES=20000
export CONT_USUARIOS=30



while [ $? != 24 ]
do
CONT_REQUISICOES=$(( CONT_REQUISICOES+70000 ))
CONT_USUARIOS=$(( CONT_USUARIOS+15 ))
export CALC=`expr $CONT_REQUISICOES / $CONT_USUARIOS`
echo "Testando com $CONT_REQUISICOES requisições e $CONT_USUARIOS usuários, isso dá em média $CALC requisições por usuário!"
ab -n $CONT_REQUISICOES -c $CONT_USUARIOS -k -q -H "Accept-Encoding: gzip, deflate" 127.0.0.1:3000/opt/app.js > output.log
done

echo "O teste de carga realizado mostrou que a aplicãção respondeu até $CONT_REQUISICOES requisições de $CONT_USUARIOS simultâneos." >> output.log


export CALC1=`expr $CONT_REQUISICOES / $CONT_USUARIOS`

echo "Isso dá um total de $CONT_REQUISICOES requisições oriundos de $CONT_USUARIOS usuários, são $CALC1 requisições por usuário"

