#!/bin/bash


CONT_REQUISICOES=1000
CONT_USUARIOS=1




while [ $? != 24 ]
do
ab -n $CONT_REQUISICOES -c $CONT_USUARIOS http://127.0.0.1:3000/opt/app.js
CONT_REQUISICOES=$(CONT_REQUISICOES+1000)
CONT_USUARIOS=$(CONT_USUARIOS+10)
done

echo "O teste de carga realizado mostrou que a aplicãção respondeu até $CONT_REQUISICOES requisições de $CONT_USUARIOS simultâneos."


CALC=`expr $CONT_REQUISICOES / $CONT_USUARIOS`

echo "Isso dá um total $CONT_REQUISICOES e $CONT_USUARIOS, $CALC requisições por usuário"
